import { Resend } from 'resend';
import dotenv from 'dotenv';
dotenv.config();

const resend = new Resend(process.env.RESEND_API_KEY);

export async function sendMeetingSummary({ to, meetingTitle, summary, decisions, actionItems, transcript }) {
  console.log('Sending email to:', to);

  const decisionsHtml = decisions.length > 0
    ? `<ul>${decisions.map(d => `<li>${d}</li>`).join('')}</ul>`
    : '<p>No key decisions recorded.</p>';

  const actionItemsHtml = actionItems.length > 0
    ? `<ul>${actionItems.map(a => `<li><strong>${a.owner}</strong> → ${a.task}${a.due ? ` <em>(${a.due})</em>` : ''}</li>`).join('')}</ul>`
    : '<p>No action items recorded.</p>';

  const { data, error } = await resend.emails.send({
    from: 'MeetMind <onboarding@resend.dev>',
    to: [to],
    subject: `Meeting Summary: ${meetingTitle}`,
    html: `
      <!DOCTYPE html>
      <html>
      <head>
        <style>
          body { font-family: -apple-system, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; color: #333; }
          .header { background: linear-gradient(135deg, #6C5CE7, #00cec9); padding: 24px; border-radius: 12px; color: white; margin-bottom: 24px; }
          .header h1 { margin: 0; font-size: 20px; }
          .header p { margin: 8px 0 0; opacity: 0.85; font-size: 14px; }
          .section { background: #f8f9fa; border-radius: 10px; padding: 16px 20px; margin-bottom: 16px; }
          .section h2 { margin: 0 0 12px; font-size: 14px; text-transform: uppercase; letter-spacing: 0.05em; color: #6C5CE7; }
          .section p { margin: 0; line-height: 1.6; font-size: 15px; }
          ul { margin: 0; padding-left: 20px; }
          li { margin-bottom: 8px; font-size: 14px; line-height: 1.5; }
          .footer { text-align: center; font-size: 12px; color: #999; margin-top: 24px; }
        </style>
      </head>
      <body>
        <div class="header">
          <h1>⚡ ${meetingTitle}</h1>
          <p>Meeting summary generated by MeetMind</p>
        </div>

        <div class="section">
          <h2>Summary</h2>
          <p>${summary}</p>
        </div>

        <div class="section">
          <h2>Key Decisions</h2>
          ${decisionsHtml}
        </div>

        <div class="section">
          <h2>Action Items</h2>
          ${actionItemsHtml}
        </div>

        <div class="footer">
          <p>Generated by <strong>MeetMind</strong> · AI-powered meeting intelligence</p>
          <p><a href="${process.env.FRONTEND_URL}">View in dashboard</a></p>
        </div>
      </body>
      </html>
    `
  });

  if (error) throw error;
  console.log('Email sent successfully:', data?.id);
  return data;
}